language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 17.5
  - 18.0
  - 19.0
before_script:
  - MIX_ENV=test mix do deps.get
  - MIX_ENV=test mix compile --warnings-as-errors
script:
  - MIX_ENV=test mix test --no-start
after_script:
  - MIX_ENV=test mix coveralls.travis --no-start
services:
  - redis-server
sudo: false
